
database:
  url: ${dburl}
  username: ${dbusername}
  password: ${dbpassword}

spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

custom:
  security:
    unsecured-endpoint:
      - /swagger-ui.html
      - /user/**
      - /actuator/**